
version: '3'
services:
  msone:
    image: msone
    container_name: msone
    build:
      context: ./ms1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - dbone
    networks:
    - netmsone 
    extra_hosts:
      - "host.docker.internal:host-gateway"  
  dbone:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=msone
    networks:
      - netmsone
    extra_hosts:
      - "host.docker.internal:host-gateway"  
  mstwo:
    image: mstwo
    container_name: mstwo
    build:
      context: ./ms2
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    extra_hosts:
      - "host.docker.internal:host-gateway"   
networks:
  netmsone:
    driver: bridge
       