server:
  port: 8080
spring:
  application:
    name: "msOne"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://host.docker.internal:5432/msone"
    username: "postgres"
    password: "password"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapter:
  restconsumer:
    url: "http://localhost:8090"
